{% set name = "pysis" %}
{% set version = "0.6.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1152489d43eb6dca8313dbfe57787580cf3ef9f8795800ad5c830f737d826b7b

build:
  skip: true  # [win]
  number: 1
  script:
    - bash tests/make_isis_env.sh
    - python setup.py install

requirements:
  build:
    - setuptools
    - python
    - numpy
    - six
    - pvl
  run:
    - python
    - pvl
    - numpy
    - six


test:
  imports:
    - pysis

about:
  home: https://github.com/wtolson/pysis
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Toolkit for using USGS Isis in Python

extra:
  recipe-maintainers:
    - kelvinrr
    - jlaura
