travis:
  secure:
    BINSTAR_TOKEN: qs9i2PU/U+JxOz8CLJ4BTYujfyxMVDhtcw/X1yi8ZLQVJeK6G06WhwKAGd2Jy6m0hXwpCdBVKWmK9GPVXzbxCMTJsrsHTsC+UR8XjM93+USa4dciaTYyWDG53gVZ6LedkLZ37rMYp0JXbRGRvB5UNcHrCRY8ilrsYvldVhnAdKwlYHrxSE6z6u32otPvHaw+ghoVpLGlS3ASuOINVQymYgcJd17BzOrQE7QwYefRwrUN9nnJuSw+PDAVQwnTBCaA6aHf1O9g9bqFroaXobKGqPNJnJsWIGcIrrg3rMmYjQMprjibl3DYE1FdN+ux8FVNpkxdHic6vBxL2sFTZtpvQJAN2qFFChtHP1BvL6t32uQvdaLMH3NkuiSMYMynhm13WJA9l2LzGPS78YBLwmdFg9YDPtpNxRQ51bjNqTS/wQCQZkIUce3qVdjZv8/SdkP5bf+XuGMGHS99A5xzp13oceBEAZ1GkmA8FPlWllj9WNjWBDOVQG1gwmEoJZYskWsJLFGkH/TAB04LGFlKDD7Zav2Eed7Sx7vGGTA0VQs8Ap7dEAXCseUqzPq0zW1jVP1UAvixu2M9wAEN+VLMHAMBxH/D+llMk0i7NBL96wUJKZMCqIbIcjob+UtcIJ34RvUtHG2yLLIUBYCDT9vV0e76Da5zqknMbyCXbgAAiUDXI2o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
